export const homeObjOne = {
  id: "home",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Software Engineer",
  headline: "Seeking Full-time Job By 2023",
  description: "Graduating May 2023",
  buttonLabel: "Hire Me!",
  imgStart: true,
  img: require("../../images/golf.svg"),
  alt: "Golf",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "home",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Software Engineer",
  headline: "Seeking Full-time Job By 2023",
  description: "Graduating May 2023",
  buttonLabel: "Hire Me!",
  imgStart: true,
  img: require("../../images/golf.svg"),
  alt: "Golf",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjThree = {
  id: "home",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Software Engineer",
  headline: "Seeking Full-time Job By 2023",
  description: "Graduating May 2023",
  buttonLabel: "Hire Me!",
  imgStart: true,
  img: require("../../images/golf.svg"),
  alt: "Golf",
  dark: true,
  primary: true,
  darkText: false,
};
